name: build-and-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22.14.0
      - run: npm cache clean --force
      - run: rm -rf node_modules package-lock.json
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm run build
